// Running the graded ramp test, rather than describing it.
//
// This is the session everything else in the plan is derived from: the heart-rate/speed fit, the
// talk-test threshold, the seed VDOT. It shipped to the phone as a paragraph — "4 min stages at 5,
// 6, 7, 8, 9 km/h" — which is a thing a person can read and not a thing an app can run. So the
// athlete stood on a treadmill timing four-minute stages by hand, trying to remember which of five
// speeds came next, during the one hour whose entire value is clean stage boundaries.
//
// The protocol itself is generated by the engine, from the same `calibration_protocol` that later
// analyses the recording, so the stages announced here and the stages the analysis expects cannot
// drift apart. This module only decides *when* each one starts.
//
// Two things it is careful about:
//
//   - The label. Every recorded sample is tagged with the stage it belongs to, and the engine's
//     stage analysis groups by exactly that. A recording with no labels is an hour on a treadmill
//     that yields a single undifferentiated blob and no fit.
//   - The final minute. Heart rate needs two to three minutes to plateau, so only the last minute of
//     each stage is used — and it is also when the talk test has to happen, which is an observation
//     no sensor can recover afterwards. It gets its own announcement.

/** A step boundary, a final-minute warning, or the end. */
export const RampEvent = {
  STEP: 'step',
  FINAL_MINUTE: 'final_minute',
  DONE: 'done',
};

export class RampRunner {
  /** @param steps the engine's `ramp.steps`, in order. */
  constructor(steps) {
    this.steps = (steps || []).map(s => ({ ...s }));
    this.index = -1;            // -1 so the first update advances into step 0 by the normal path
    this.until = 0;
    this.warned = new Set();
    this.done = false;
  }

  get step() { return this.index >= 0 ? this.steps[this.index] : null; }

  /** What a sample recorded now should be labelled with. `stage_3`, `warmup`, `steady`, ... */
  get label() {
    const s = this.step;
    if (!s) return '';
    return s.kind === 'stage' ? `stage_${s.index}` : s.kind;
  }

  /** Seconds remaining in the current step, or 0. */
  remaining(tS) { return Math.max(0, this.until - tS); }

  /**
   * Feed one second. Returns an event or null.
   *
   * Only ever advances one step per call: a step of zero or negative length would otherwise run the
   * whole protocol inside a single tick and announce six stages at once.
   */
  update(tS) {
    if (this.done) return null;

    const cur = this.step;
    if (cur && cur.measure_last_s && !this.warned.has(this.index)) {
      const left = this.until - tS;
      if (left > 0 && left <= cur.measure_last_s) {
        this.warned.add(this.index);
        return { kind: RampEvent.FINAL_MINUTE, step: cur, index: this.index };
      }
    }

    if (tS < this.until) return null;

    this.index += 1;
    const next = this.step;
    if (!next) {
      this.done = true;
      return { kind: RampEvent.DONE };
    }
    // Guard against a zero-length step: a protocol with one would otherwise never let the clock
    // catch up, and every subsequent tick would fire another boundary.
    this.until = tS + Math.max(1, Math.round(Number(next.minutes || 0) * 60));
    return { kind: RampEvent.STEP, step: next, index: this.index };
  }

  /** Total protocol length in seconds, for the display before it starts. */
  totalS() {
    return this.steps.reduce((a, s) => a + Math.max(1, Math.round(Number(s.minutes || 0) * 60)), 0);
  }
}
