#!/usr/bin/env python3
"""Sleep spindles as an anatomically specific test of the thalamocortical account.

WHY SPINDLES AND NOT THE SLOWING FLAG. The thalamocortical account came out of R389: the clinician's
generalized-slowing flag carries a *larger* protective effect after anoxia (interaction −0.750 [−1.433,
−0.116]) than after other aetiologies, which a generic-severity account does not predict. But that flag is a
poor instrument -- 83.8 % prevalent, and its positivity collapses from 92.7 % to 56.1 % across the burden
range because a reader calls a near-suppressed record *suppressed* rather than *slow* (R386).

**Sleep spindles are generated by the thalamic reticular nucleus.** They are the most anatomically specific
readout of thalamocortical integrity available in a routine EEG report, and they are annotated on all 49,232
HEEDB patients. If the thalamocortical account is right, it should show up here more sharply than it did in
the flag -- and if it does not, the account loses its best chance.

------------------------------------------------------------------------------------------------------------
THE CONFOUND, STATED FIRST BECAUSE IT WOULD OTHERWISE SINK THIS.

Sleep architecture requires a patient who cycles. **A comatose patient has no spindles by definition**, so
"spindles present" is substantially "not deeply encephalopathic", and the raw association with survival is
near-meaningless on its own. Everything below is built to ask the only question worth asking: do spindles
carry information **beyond depth of encephalopathy**, and is that residual **aetiology-dependent**?

Two depth adjustments are used, and the difference between them matters:
  - **burden** — quantitative suppression burden, continuous, measured from the raw EEG. The primary control.
  - **the `awake` report flag** — a direct arousability marker read by the same clinician from the same
    recording. This is the aggressive control: spindles and wakefulness are both downstream of arousability,
    so adjusting for it removes much of what spindles could indicate. Reported as a sensitivity, and a
    spindle effect that survives it is hard to attribute to arousability alone.

------------------------------------------------------------------------------------------------------------
REGISTERED, before the data was looked at.

  S1  Spindles present marks lower 30-day death. Expected, confounded, and reported only as a baseline --
      it establishes nothing on its own.
  S2  The association survives adjustment for suppression burden.
      FALSIFIED IF it does not, in which case spindles are a depth proxy and this line closes.
  S3  DECISIVE, and it is the fork that separates the two accounts. The spindle effect is **LARGER after
      anoxia**, because the thalamus is selectively vulnerable to global hypoxia-ischaemia and usually
      structurally spared in toxic/metabolic encephalopathy -- so preserved spindles certify more where
      thalamic damage is likely.
      **A generic-severity account predicts NO aetiology interaction.** FALSIFIED IF the interaction is
      absent or runs the other way.
  S4  SENSITIVITY. The same, additionally adjusted for the `awake` flag.

WHAT A POSITIVE WOULD AND WOULD NOT BUY. It would not establish a mechanism -- L2 and L3 stand, 46 % die
inside the withdrawal window. It would give the thalamocortical account an anatomically specific instrument
agreeing with a non-specific one, which is convergent evidence of a kind this project has not had.
"""
import csv, io, os, sys
from collections import defaultdict
from datetime import datetime

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from icare_morph_replication import logit_fit, auc

AP = "arn:aws:s3:us-east-1:184438910517:accesspoint/bdsp-credentialed-access-point"
OMOP = os.environ.get("OMOP_OUT", "/tmp/eeg_probe/heedb_omop")
BURDEN = os.environ.get("HEEDB_BURDEN", "/tmp/eeg_probe/heedb_bs_burden_win.s*.csv")
AETCACHE = os.environ.get("AET_CACHE", "/tmp/eeg_probe/heedb_aetiology.csv")
NBOOT = int(os.environ.get("NBOOT", "1500"))


def dt(s):
    s = (s or "").strip()
    for f in ("%Y-%m-%d %H:%M:%S", "%Y-%m-%d %H:%M:%S.%f", "%Y-%m-%d"):
        try:
            return datetime.strptime(s, f)
        except ValueError:
            continue
    return None


def median_by_patient(pattern, col):
    import glob
    d = defaultdict(list)
    for path in sorted(glob.glob(pattern)):
        for r in csv.DictReader(open(path)):
            p = (r.get("patient") or "").strip()
            try:
                v = float(r[col])
            except (KeyError, TypeError, ValueError):
                continue
            if p.isdigit() and v == v:
                d[int(p)].append(v)
    return {p: float(np.median(v)) for p, v in d.items()}


def boot_coef(X, y, col, rng, reps):
    out, n = [], len(y)
    for _ in range(reps):
        i = rng.integers(0, n, n)
        if 0 < y[i].sum() < n:
            try:
                out.append(float(logit_fit(X[i], y[i])[col]))
            except Exception:
                continue
    if len(out) < 50:
        return float("nan"), float("nan")
    return tuple(np.percentile(out, [2.5, 97.5]))


def main():
    rng = np.random.default_rng(20260727)
    import boto3
    from botocore.config import Config
    s3 = boto3.client("s3", region_name="us-east-1",
                      config=Config(s3={"payload_signing_enabled": False}))

    spin, awake, when = {}, {}, {}
    for st in ("S0001", "S0002"):
        txt = s3.get_object(Bucket=AP,
                            Key=f"EEG/HEEDB_Metadata/{st}_EEG__reports_findings.csv"
                            )["Body"].read().decode("utf-8", "replace")
        rd = csv.DictReader(io.StringIO(txt))
        for c in ("spindles", "awake"):
            assert c in (rd.fieldnames or []), f"column '{c}' missing from {st} findings"
        for r in rd:
            p = (r.get("BDSPPatientID") or "").strip()
            if not p.isdigit():
                continue
            p = int(p)
            spin[p] = spin.get(p, False) or ((r.get("spindles") or "").strip() not in ("", "None", "nan"))
            awake[p] = awake.get(p, False) or ((r.get("awake") or "").strip() not in ("", "None", "nan"))
            t = dt(r.get("EndTime(EEG)") or r.get("StartTime(EEG)") or "")
            if t and (p not in when or t < when[p]):
                when[p] = t

    death = {}
    with open(f"{OMOP}/death.csv") as fh:
        for r in csv.DictReader(fh):
            try:
                death[int(r["person_id"])] = dt(r.get("death_datetime"))
            except (KeyError, TypeError, ValueError):
                pass

    anox = {}
    assert os.path.exists(AETCACHE), f"{AETCACHE} missing -- run analysis/heedb_content_sign_flip.py first"
    for r in csv.DictReader(open(AETCACHE)):
        anox[int(r["pid"])] = r["anoxic"] == "1"

    burden = median_by_patient(BURDEN, "burden")
    assert burden, "burden table empty"

    # No death-ascertainment conditioning: absent record = alive (the R393 convention).
    rows = []
    for p, b in burden.items():
        if p not in when or p not in spin or p not in anox:
            continue
        d = death.get(p)
        if d is not None and (d - when[p]).days < -1:
            continue
        y = 1.0 if (d is not None and (d - when[p]).days <= 30) else 0.0
        rows.append((y, 1.0 if spin[p] else 0.0, b, 1.0 if anox[p] else 0.0,
                     1.0 if awake.get(p) else 0.0))
    assert len(rows) >= 500, f"only {len(rows)} patients -- check the joins"
    y = np.array([r[0] for r in rows]); sp = np.array([r[1] for r in rows])
    b = np.array([r[2] for r in rows]); ax = np.array([r[3] for r in rows])
    aw = np.array([r[4] for r in rows])
    n = len(y)
    print(f"cohort: {n:,}   30-day death {100*y.mean():.1f}%   spindles {100*sp.mean():.1f}%   "
          f"anoxic {100*ax.mean():.1f}%   awake-flagged {100*aw.mean():.1f}%")

    print("\n" + "=" * 96)
    print("S1  BASELINE (confounded by arousability -- establishes nothing on its own)")
    print("=" * 96)
    print(f"   30-day death: spindles present {100*y[sp==1].mean():.1f}%   absent {100*y[sp==0].mean():.1f}%")
    print(f"   spindle prevalence by burden quartile (the confound, made visible):")
    qs = np.quantile(b, [.25, .5, .75])
    ed = [-1e-9] + list(qs) + [1.01]
    for i in range(4):
        m = (b > ed[i]) & (b <= ed[i + 1])
        if m.sum() > 30:
            print(f"      burden {ed[i]:.3f}-{ed[i+1]:.3f}  n={int(m.sum()):>5}  "
                  f"spindles {100*sp[m].mean():5.1f}%   30-d death {100*y[m].mean():5.1f}%")

    one = np.ones(n)
    print("\n" + "=" * 96)
    print("S2  DOES IT SURVIVE ADJUSTMENT FOR SUPPRESSION BURDEN?")
    print("=" * 96)
    X2 = np.column_stack([one, b, sp])
    c2 = logit_fit(X2, y)
    l2, h2 = boot_coef(X2, y, 2, rng, NBOOT)
    print(f"   spindle coefficient adjusted for burden {c2[2]:+.3f} [{l2:+.3f},{h2:+.3f}]   (burden {c2[1]:+.3f})")
    s2ok = l2 == l2 and l2 * h2 > 0 and c2[2] < 0
    print(f"   S2 {'CONFIRMED -- protective beyond depth' if s2ok else ('REVERSED' if l2 == l2 and l2 > 0 else 'FALSIFIED -- spindles are a depth proxy')}")

    print("\n" + "=" * 96)
    print("S3  DECISIVE -- IS THE SPINDLE EFFECT AETIOLOGY-DEPENDENT?")
    print("=" * 96)
    for lab, m in (("anoxic", ax == 1), ("non-anoxic", ax == 0)):
        k = int(m.sum())
        if k < 150 or not (0 < y[m].sum() < k) or sp[m].sum() < 20 or (1 - sp[m]).sum() < 20:
            print(f"   {lab:<11} n={k:>5}  too few to estimate")
            continue
        Xs = np.column_stack([np.ones(k), b[m], sp[m]])
        cs = logit_fit(Xs, y[m])
        lo, hi = boot_coef(Xs, y[m], 2, rng, NBOOT)
        print(f"   {lab:<11} n={k:>5}  death {100*y[m].mean():5.1f}%  spindles {100*sp[m].mean():5.1f}%   "
              f"spindle coef {cs[2]:+.3f} [{lo:+.3f},{hi:+.3f}]")
    Xi = np.column_stack([one, b, ax, sp, sp * ax])
    ci = logit_fit(Xi, y)
    li, hi_ = boot_coef(Xi, y, 4, rng, NBOOT)
    print(f"\n   INTERACTION spindles x anoxic {ci[4]:+.3f} [{li:+.3f},{hi_:+.3f}]")
    print(f"   (spindle effect in non-anoxic {ci[3]:+.3f}; implied in anoxic {ci[3]+ci[4]:+.3f})")
    if li == li and li * hi_ > 0:
        if ci[4] < 0:
            print("   S3 CONFIRMED -- spindles matter MORE after anoxia, as the thalamocortical account")
            print("   predicts and a generic-severity account does not.")
        else:
            print("   S3 REVERSED -- spindles matter LESS after anoxia. The account does not predict this.")
    else:
        print("   S3 FALSIFIED -- no aetiology interaction. The thalamocortical account gains nothing over")
        print("   generic severity here, and this was its best available instrument.")

    print("\n" + "=" * 96)
    print("S4  SENSITIVITY -- additionally adjusted for the `awake` flag (the aggressive control)")
    print("=" * 96)
    X4 = np.column_stack([one, b, aw, ax, sp, sp * ax])
    c4 = logit_fit(X4, y)
    l4, h4 = boot_coef(X4, y, 5, rng, NBOOT)
    lm, hm = boot_coef(X4, y, 4, rng, NBOOT)
    print(f"   spindle main effect {c4[4]:+.3f} [{lm:+.3f},{hm:+.3f}]   "
          f"interaction x anoxic {c4[5]:+.3f} [{l4:+.3f},{h4:+.3f}]")
    print("   Spindles and wakefulness are both downstream of arousability, so this is deliberately")
    print("   over-controlled. Survival here is strong evidence; failure here is not fatal on its own.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
