#!/usr/bin/env python3
"""Extract INTERPRETABLE burst morphology from raw HEEDB EEG: can fatal and benign suppression be told apart?

WHY MORPHOLOGY, AND WHY THESE FEATURES. Reversibility was tested first and explains only 8.8 % of the aetiology
interaction (docs/LESSONS.md), so what makes post-anoxic suppression different is not mainly that it fails to
resolve. The next hypothesis is that it is a different STATE, distinguishable in the bursts themselves.

The mechanism that predicts the direction of every feature below:
  * GABA-ergic / metabolic suppression happens in a cortex that is INTACT but hyperpolarised. The
    thalamocortical machinery still exists, so bursts are generated by a rich, variable network and retain the
    fast rhythms that machinery produces.
  * Post-anoxic suppression happens in a cortex that has LOST NEURONS, interneurons especially. The surviving
    network is impoverished and few pathways remain, so bursts are near-copies of one another, and the
    oscillatory machinery that made alpha and beta is gone.
This is the "identical bursts" phenomenon described after cardiac arrest, and it is a claim about tissue rather
than about milieu -- which is why it can differ at the same suppression BURDEN, the fact that defeated the
depth explanation (section 6b of the findings document: the burden->death SLOPE differs by aetiology).

EXPLAINABILITY IS A DESIGN CONSTRAINT, NOT A PREFERENCE. Every feature here is a named physiological quantity
with a stated mechanism and a predicted sign, computed by arithmetic a clinician can follow. There is no learned
representation, no embedding and no opaque classifier anywhere in this analysis; the final discriminator is a
handful of named terms with signed coefficients that can be read off and argued with. A feature that cannot be
explained is not admitted, however well it might predict.

FEATURES, each with its mechanism and predicted direction in post-anoxic injury:
  stereotypy      mean pairwise correlation between time-aligned bursts. Impoverished network -> near-copies.
                  PREDICTED HIGHER after anoxia. This is the primary feature.
  alpha_beta      fraction of intra-burst power in 8-30 Hz. Thalamocortical loops make alpha/beta; anoxia
                  destroys them. PREDICTED LOWER after anoxia.
  burst_amp       median peak-to-peak amplitude within bursts (uV).
  burst_dur       median burst duration (s).
  burst_rate      bursts per minute.
  supp_cv         coefficient of variation of suppression-interval durations -- regularity of the cycle.
                  Registered as EXPLORATORY: the direction is not confidently predicted, so it is reported but
                  does not count for or against the hypothesis.

METHOD. Bursts are the complement of the suppression mask produced by heedb_bs_calibrate.burden, which is the
detector calibrated in-distribution against HEEDB's own expert labels (AUC 0.829 in calibration, 0.783
out-of-sample on this cohort). The mask logic is reimplemented here ONLY because burden() returns a fraction and
not the mask itself; the frame length, threshold and minimum-run rule are taken from it unchanged so the burst
segmentation is identical to the one that was validated. prep() and bids_key() are imported, not copied.

Sharded and resumable: --shard i --nshards N, one output file per shard.
"""
import argparse, csv, io, os, sys, time
from collections import defaultdict

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

THRESH_UV = float(os.environ.get("BS_THRESH_UV", "5.0"))
N_WINDOWS = int(os.environ.get("N_WINDOWS", "4"))
WIN_SECONDS = int(os.environ.get("WIN_SECONDS", "120"))
LEAD_IN_FRAC = float(os.environ.get("LEAD_IN_FRAC", "0.15"))
OUT = os.environ.get("MORPH_OUT", "/tmp/eeg_probe/heedb_burst_morph.csv")
FRAME_S, MIN_RUN_S, MIN_BURST_S = 0.1, 0.5, 0.3

COLS = ["site", "patient", "bids", "session", "n_bursts", "stereotypy", "alpha_beta",
        "burst_amp", "burst_dur", "burst_rate", "supp_cv", "burden"]


def suppression_mask(x, fs, thresh):
    """The mask behind heedb_bs_calibrate.burden -- same frame length, threshold and min-run rule."""
    fr = max(1, int(FRAME_S * fs)); n = len(x) // fr
    if n < 20:
        return None, None
    seg = x[:n * fr].reshape(n, fr)
    ptp = seg.max(axis=1) - seg.min(axis=1)
    dead = ptp < 1e-6                       # amplifier off / zero padding, not physiology
    supp = (ptp < thresh) & (~dead)
    need = max(1, int(MIN_RUN_S / FRAME_S)); run = 0; out = supp.copy()
    for i in range(n):
        if supp[i]:
            run += 1
        else:
            if run < need:
                out[max(0, i - run):i] = False
            run = 0
    return out, dead


def runs_of(mask, value):
    """[(start,end)] index runs where mask == value."""
    out, i, n = [], 0, len(mask)
    while i < n:
        if mask[i] == value:
            j = i
            while j < n and mask[j] == value:
                j += 1
            out.append((i, j)); i = j
        else:
            i += 1
    return out


def morphology(x, fs, thresh):
    x = np.asarray(x, float)
    x = x[np.isfinite(x)]
    if len(x) < fs * 20:
        return None
    supp, dead = suppression_mask(x, fs, thresh)
    if supp is None or dead.mean() > 0.5:
        return None
    fr = max(1, int(FRAME_S * fs))
    burden = float(supp.sum() / max(1, (~dead).sum()))
    bursts = [(a, b) for a, b in runs_of(supp, False)
              if (b - a) * FRAME_S >= MIN_BURST_S]
    supp_runs = [(b - a) * FRAME_S for a, b in runs_of(supp, True)]
    if len(bursts) < 4:
        return None

    segs, amps, durs = [], [], []
    for a, b in bursts:
        w = x[a * fr:b * fr]
        if len(w) < int(0.2 * fs):
            continue
        segs.append(w)
        amps.append(float(w.max() - w.min()))
        durs.append((b - a) * FRAME_S)
    if len(segs) < 4:
        return None

    # ---- stereotypy: mean pairwise correlation of time-aligned burst onsets --------------------------
    # Bursts are aligned on ONSET and compared over a fixed 1 s window, so the statistic measures waveform
    # similarity and not merely similar duration. Bursts shorter than the window are excluded from this
    # feature rather than zero-padded, since padding manufactures correlation between short bursts.
    L = int(1.0 * fs)
    al = [s[:L] for s in segs if len(s) >= L]
    stereo = float("nan")
    if len(al) >= 4:
        M = np.vstack(al)
        M = M - M.mean(axis=1, keepdims=True)
        sd = M.std(axis=1)
        keep = sd > 1e-9
        M, sd = M[keep], sd[keep]
        if len(M) >= 4:
            C = (M @ M.T) / (len(M[0]) * np.outer(sd, sd))
            iu = np.triu_indices(len(M), k=1)
            stereo = float(np.nanmean(C[iu]))

    # ---- intra-burst spectral content ---------------------------------------------------------------
    ab = []
    for s in segs:
        if len(s) < int(0.5 * fs):
            continue
        f = np.fft.rfftfreq(len(s), 1.0 / fs)
        P = np.abs(np.fft.rfft(s * np.hanning(len(s)))) ** 2
        lo = (f >= 1) & (f <= 30); hi = (f >= 8) & (f <= 30)
        tot = P[lo].sum()
        if tot > 0:
            ab.append(float(P[hi].sum() / tot))
    total_s = len(x) / fs
    return dict(n_bursts=len(segs),
                stereotypy=stereo,
                alpha_beta=float(np.median(ab)) if ab else float("nan"),
                burst_amp=float(np.median(amps)),
                burst_dur=float(np.median(durs)),
                burst_rate=float(60.0 * len(segs) / max(total_s, 1e-9)),
                supp_cv=(float(np.std(supp_runs) / np.mean(supp_runs))
                         if len(supp_runs) >= 3 and np.mean(supp_runs) > 0 else float("nan")),
                burden=burden)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--shard", type=int, default=0)
    ap.add_argument("--nshards", type=int, default=1)
    ap.add_argument("--limit", type=int, default=0)
    args = ap.parse_args()
    if not (0 <= args.shard < args.nshards):
        print("bad shard"); return 2

    import boto3, glob as _glob
    from botocore.config import Config
    from heedb_edf_range import read_edf_window, AP
    from heedb_bs_calibrate import prep, bids_key

    s3 = boto3.client("s3", region_name="us-east-1",
                      config=Config(s3={"payload_signing_enabled": False},
                                    retries={"max_attempts": 4, "mode": "standard"}))

    want = {int(x) for x in open("/tmp/heedb_bs_patients.txt").read().split() if x.strip().isdigit()}
    print(f"burst-suppression patients targeted: {len(want)}")

    recs = []
    for site in ("S0001", "S0002"):
        try:
            txt = s3.get_object(Bucket=AP,
                                Key=f"EEG/eeg-metadata/{site}_eeg_metadata_2026_04_30.csv"
                                )["Body"].read().decode("utf-8", "replace")
        except Exception as e:
            print(f"  {site}: {type(e).__name__}"); continue
        for r in csv.DictReader(io.StringIO(txt)):
            pid = (r.get("BDSPPatientID") or "").strip()
            bids = (r.get("BidsFolder") or "").strip()
            if not pid.isdigit() or not bids or int(pid) not in want:
                continue
            recs.append((site, pid, bids, (r.get("EEGFolder") or "").strip(),
                         (r.get("SessionID") or "").strip()))
    print(f"recordings for those patients: {len(recs)}")
    if os.environ.get("FIRST_PER_PATIENT", "1") == "1":
        # One recording per patient -- the earliest session. The outcome analysis anchors on each patient's
        # INDEX EEG (earliest report time), so morphology must be measured on the same recording; averaging a
        # patient's later recordings in would mix the index state with whatever followed it, including
        # recordings taken after the cause had been treated. Also cuts 44,535 recordings to ~7,000.
        best = {}
        for r in recs:
            try:
                sess = int(r[4])
            except Exception:
                continue
            if r[1] not in best or sess < best[r[1]][0]:
                best[r[1]] = (sess, r)
        recs = [v[1] for v in best.values()]
        print(f"restricted to the earliest session per patient: {len(recs)}")

    out_path = OUT if args.nshards == 1 else OUT[:-4] + f".s{args.shard}.csv"
    done = set()
    for p in sorted(set([OUT] + _glob.glob(OUT[:-4] + ".s*.csv"))):
        if os.path.exists(p):
            for r in csv.DictReader(open(p)):
                done.add((r["site"], r["bids"], r["session"]))
    todo = [x for x in recs if (x[0], x[2], x[4]) not in done]
    if args.nshards > 1:
        todo = todo[args.shard::args.nshards]
    if args.limit:
        todo = todo[:args.limit]
    print(f"already done {len(done)}, to do {len(todo)} (shard {args.shard}/{args.nshards} -> {out_path})")

    newf = not os.path.exists(out_path)
    fh = open(out_path, "a", newline=""); w = csv.writer(fh)
    if newf:
        w.writerow(COLS); fh.flush()

    t0 = time.time(); ok = 0
    for i, (site, pid, bids, eegfolder, sess) in enumerate(todo, 1):
        try:
            key = bids_key(site, bids, sess, eegfolder)
            acc = []
            for j in range(N_WINDOWS):
                frac = LEAD_IN_FRAC + (0.70 * j / max(N_WINDOWS - 1, 1))
                try:
                    X, fs, names, meta = read_edf_window(key, max_seconds=WIN_SECONDS, s3=s3,
                                                         start_frac=frac)
                except Exception:
                    continue
                chans = prep(X, names, fs)
                if not chans:
                    continue
                # per-window: median across channels of each feature, then median across windows
                per = [morphology(c, fs, THRESH_UV) for c in chans]
                per = [d for d in per if d]
                if per:
                    acc.append({k: float(np.nanmedian([d[k] for d in per])) for k in per[0]})
            if acc:
                agg = {k: float(np.nanmedian([d[k] for d in acc])) for k in acc[0]}
                w.writerow([site, pid, bids, sess, int(agg["n_bursts"])]
                           + [round(agg[k], 5) for k in
                              ("stereotypy", "alpha_beta", "burst_amp", "burst_dur",
                               "burst_rate", "supp_cv", "burden")])
                fh.flush(); ok += 1
        except Exception:
            continue
        if i % 25 == 0:
            el = (time.time() - t0) / 60
            print(f"  [{i}/{len(todo)}] {ok} with morphology ({el:.1f} min, {i/max(el,1e-9):.1f} rec/min)",
                  flush=True)
    fh.close()
    print(f"DONE: {ok} recordings with burst morphology -> {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
