#!/usr/bin/env python3
"""Can fatal and benign burst suppression be told apart from the bursts themselves -- explainably?

CONTEXT. docs/research/39_HEEDB_FINDINGS.md shows THAT suppression means different things by aetiology
(interaction spread 38.51 pp). Two mechanisms have been tested:
  DEPTH      ruled out -- the burden->death SLOPE differs by aetiology, so it is not simply "more suppression".
  REVERSIBILITY  real but small -- persistence explains 8.8 % of the interaction (docs/LESSONS.md).
This tests the third: the bursts are a different KIND of burst.

MECHANISM, which predicts the sign of every feature before any model is fit.
  GABA-ergic and metabolic suppression occur in a cortex that is intact but hyperpolarised: the thalamocortical
  machinery survives, so bursts are generated by a rich variable network and keep the fast rhythms that
  machinery makes. Post-anoxic suppression occurs in a cortex that has lost neurons, interneurons especially:
  the surviving network is impoverished, few pathways remain, bursts become near-copies of one another, and the
  oscillatory machinery that produced alpha and beta is gone. This is a claim about TISSUE rather than MILIEU,
  which is why it can differ at identical suppression burden.

REGISTERED PREDICTIONS. Note the thresholds: B3 states an EFFECT SIZE, not merely a direction. The previous
mechanism test (reversibility) passed a direction-only criterion while explaining 8.8 % of the effect, which is
not what a mechanism claim means (docs/LESSONS.md).
  B1  Burst STEREOTYPY is higher in anoxic patients than in sepsis/metabolic.
      FALSIFIED IF anoxic is not the highest term, or the across-aetiology spread covers zero.
  B2  Intra-burst ALPHA/BETA fraction is lower in anoxic patients.
      FALSIFIED IF anoxic is not the lowest term, or the spread covers zero.
  B3  MECHANISM. Adding the morphology features to the outcome model absorbs >= 50 % of the aetiology
      interaction spread.
      FALSIFIED IF the absorbed fraction is < 50 %, EVEN IF the attenuation is statistically significant.
  B4  DISCRIMINATION. Among burst-suppression patients, morphology separates those who die within 30 days from
      those who do not, with AUC >= 0.65 using at most five named features.
      FALSIFIED IF AUC < 0.65 or its bootstrap interval includes 0.5.

  supp_cv is EXPLORATORY -- its direction was not confidently predicted, so it is reported but counts neither
  for nor against.

EXPLAINABILITY IS A CONSTRAINT. Every term is a named physiological quantity with a mechanism and a signed
coefficient that can be read off and argued with. No learned representation, no embedding, no opaque classifier.
A feature that predicts well but cannot be explained is not admitted. The discriminator is deliberately a linear
model on standardised features so each coefficient is a per-standard-deviation risk difference in percentage
points -- the units a clinician can check against their own experience.

LIMITS, in advance. Morphology is measured on the INDEX EEG only. Sampling is four 120 s windows, so features
carry real measurement error, which attenuates coefficients toward null. Indication bias is unchanged from the
parent study. Nothing here is causal.
"""
import csv, glob, os, sys
from collections import defaultdict

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from heedb_bs_ascertainment import AETIOLOGY, norm, dt, eeg_times

OMOP = os.environ.get("OMOP_OUT", "/tmp/eeg_probe/heedb_omop")
NBOOT = int(os.environ.get("NBOOT", "2000"))
FEATS = ["stereotypy", "alpha_beta", "burst_amp", "burst_dur", "burst_rate"]


def lpm(X, y):
    return np.linalg.lstsq(X, y, rcond=None)[0]


def auc(y, s):
    o = np.argsort(s); r = np.empty(len(s), float); r[o] = np.arange(1, len(s) + 1)
    n1 = float(y.sum()); n0 = float(len(y) - n1)
    if n1 == 0 or n0 == 0:
        return float("nan")
    return float((r[y == 1].sum() - n1 * (n1 + 1) / 2) / (n1 * n0))


def main():
    rng = np.random.default_rng(20260726)

    morph = {}
    for f in sorted(glob.glob("/tmp/eeg_probe/heedb_burst_morph*.csv")):
        for r in csv.DictReader(open(f)):
            try:
                p = int(r["patient"])
            except Exception:
                continue
            d = {}
            for k in FEATS + ["supp_cv", "burden"]:
                try:
                    d[k] = float(r[k])
                except Exception:
                    d[k] = float("nan")
            morph[p] = d
    print(f"patients with burst morphology: {len(morph):,}")
    if len(morph) < 300:
        print("*** too few yet; rerun when extraction has progressed"); return 1

    aet, cond_seen = defaultdict(set), set()
    with open(f"{OMOP}/condition_occurrence.csv") as fh:
        for r in csv.DictReader(fh):
            try:
                p = int(r["person_id"])
            except Exception:
                continue
            cond_seen.add(p)
            c = norm(r.get("condition_source_value"))
            if not c:
                continue
            for lab, pre in AETIOLOGY.items():
                if any(c.startswith(x) for x in pre):
                    aet[p].add(lab)

    death = {}
    with open(f"{OMOP}/death.csv") as fh:
        for r in csv.DictReader(fh):
            try:
                death[int(r["person_id"])] = dt(r.get("death_datetime"))
            except Exception:
                pass

    et = eeg_times()   # BS-labelled patients only, which is exactly this cohort
    keys = list(AETIOLOGY)
    rows = []
    for p, d in morph.items():
        if p not in cond_seen or any(d[k] != d[k] for k in FEATS):
            continue
        dd, t = death.get(p), et.get(p)
        if dd is None or t is None:
            continue
        days = (dd - t).days
        if days < -1:
            continue
        labs = aet.get(p, set())
        rows.append(dict(d30=1.0 if days <= 30 else 0.0,
                         **{k: d[k] for k in FEATS + ["supp_cv", "burden"]},
                         **{k: (1.0 if k in labs else 0.0) for k in keys}))
    n = len(rows)
    print(f"analysable (morphology + ascertained death + EEG time + condition data): {n:,}")
    if n < 300:
        print("*** insufficient"); return 1
    y = np.asarray([r["d30"] for r in rows], float)
    print(f"   died within 30 days: {100*y.mean():.1f} %")

    # standardise features so coefficients are per-SD risk differences a clinician can read
    Z = {}
    for k in FEATS + ["supp_cv"]:
        v = np.asarray([r[k] for r in rows], float)
        m, s = np.nanmean(v), np.nanstd(v)
        Z[k] = (v - m) / (s if s > 1e-12 else 1.0)
        print(f"   {k:11s} mean {m:8.3f}  SD {s:7.3f}")

    expo = [k for k in keys if sum(r[k] for r in rows) >= 30]

    # ---- B1 / B2: do the features differ by aetiology? ----------------------------------------------
    for feat, pred, tag in (("stereotypy", "highest", "B1"), ("alpha_beta", "lowest", "B2")):
        print(f"\n=== {tag}: {feat} by aetiology (standardised units, LPM) ===")
        X = np.column_stack([np.ones(n)] + [np.asarray([r[k] for r in rows], float) for k in expo])
        b = lpm(X, Z[feat])
        bt = defaultdict(list); sp = []
        for _ in range(NBOOT):
            i = rng.integers(0, n, n)
            try:
                b2 = lpm(X[i], Z[feat][i])
            except Exception:
                continue
            for j in range(1, len(expo) + 1):
                bt[j].append(b2[j])
            sp.append(float(max(b2[1:len(expo)+1]) - min(b2[1:len(expo)+1])))
        for j, k in enumerate(expo, 1):
            lo, hi = np.percentile(bt[j], [2.5, 97.5])
            print(f"   {k:12s} {b[j]:+7.3f} SD [{lo:+7.3f},{hi:+7.3f}] {'*' if (lo>0 or hi<0) else 'ns'}")
        lo, hi = np.percentile(sp, [2.5, 97.5])
        vals = b[1:len(expo)+1]
        who = expo[int(np.argmax(vals))] if pred == "highest" else expo[int(np.argmin(vals))]
        okp = (who == "anoxic" and lo > 0)
        print(f"   spread {max(vals)-min(vals):.3f} SD [{lo:.3f},{hi:.3f}]   {pred}: {who}")
        print(f"   {tag} {'CONFIRMED' if okp else 'FALSIFIED'} (predicted anoxic {pred})")

    # ---- B3: does morphology absorb the aetiology interaction? --------------------------------------
    print("\n=== B3: does burst morphology ABSORB the aetiology spread in the outcome model? ===")

    def design(idx, with_morph):
        cols = [np.ones(len(idx))]
        for k in expo:
            cols.append(np.asarray([rows[i][k] for i in idx], float))
        cols.append(np.asarray([rows[i]["burden"] for i in idx], float))   # depth held constant throughout
        if with_morph:
            for k in FEATS:
                cols.append(Z[k][idx])
        return np.column_stack(cols)

    allidx = np.arange(n)
    bo = lpm(design(allidx, False), y)
    bw = lpm(design(allidx, True), y)
    ne = len(expo)
    s_wo = float(max(bo[1:ne+1]) - min(bo[1:ne+1]))
    s_w = float(max(bw[1:ne+1]) - min(bw[1:ne+1]))
    dif = []
    for _ in range(NBOOT):
        i = rng.integers(0, n, n)
        try:
            a = lpm(design(i, False), y[i]); c = lpm(design(i, True), y[i])
        except Exception:
            continue
        dif.append((max(a[1:ne+1]) - min(a[1:ne+1])) - (max(c[1:ne+1]) - min(c[1:ne+1])))
    lo, hi = np.percentile(dif, [2.5, 97.5])
    frac = (s_wo - s_w) / max(s_wo, 1e-9)
    print(f"   aetiology spread WITHOUT morphology : {100*s_wo:.2f} pp")
    print(f"   aetiology spread WITH morphology    : {100*s_w:.2f} pp")
    print(f"   attenuation, paired bootstrap       : {100*(s_wo-s_w):+.2f} pp [{100*lo:+.2f},{100*hi:+.2f}]")
    print(f"   FRACTION ABSORBED                   : {100*frac:.1f} %   (registered threshold: 50 %)")
    print(f"   B3 {'CONFIRMED' if (frac >= 0.50 and lo > 0) else 'FALSIFIED'}")

    # ---- B4: explainable discrimination -------------------------------------------------------------
    print("\n=== B4: can fatal and benign suppression be told apart, using named features only? ===")
    Xd = np.column_stack([np.ones(n)] + [Z[k] for k in FEATS])
    bd = lpm(Xd, y)
    print("   linear probability model, per +1 SD of each named feature:")
    bt = defaultdict(list)
    for _ in range(NBOOT):
        i = rng.integers(0, n, n)
        try:
            b2 = lpm(Xd[i], y[i])
        except Exception:
            continue
        for j in range(1, len(FEATS) + 1):
            bt[j].append(b2[j])
    for j, k in enumerate(FEATS, 1):
        lo2, hi2 = np.percentile(bt[j], [2.5, 97.5])
        print(f"      {k:11s} {100*bd[j]:+7.2f} pp/SD [{100*lo2:+7.2f},{100*hi2:+7.2f}] "
              f"{'*' if (lo2>0 or hi2<0) else 'ns'}")
    sc = Xd @ bd
    a0 = auc(y, sc)
    ab = []
    for _ in range(NBOOT):
        i = rng.integers(0, n, n)
        if y[i].sum() in (0, len(i)):
            continue
        try:
            ab.append(auc(y[i], design_score(Xd, y, i)))
        except Exception:
            continue
    if ab:
        lo3, hi3 = np.percentile(ab, [2.5, 97.5])
        print(f"   AUC {a0:.3f} [{lo3:.3f},{hi3:.3f}]   (registered threshold: >= 0.65, interval excluding 0.5)")
        print(f"   B4 {'CONFIRMED' if (a0 >= 0.65 and lo3 > 0.5) else 'FALSIFIED'}")
    print("\n   Every term above is a named physiological quantity with a mechanism and a signed coefficient.")
    print("   No learned representation is used anywhere, so the model can be read, checked and disagreed with.")
    print("   AUC is in-sample and therefore optimistic; it is reported as a descriptive separation, not as a")
    print("   validated classifier, and no clinical use is claimed on this basis.")
    return 0


def design_score(Xd, y, i):
    b = lpm(Xd[i], y[i])
    return Xd[i] @ b


if __name__ == "__main__":
    sys.exit(main())
