#!/usr/bin/env python3
"""EXTERNAL TEST OF A MECHANISM: are the bursts of a surviving brain long and slow, in a second cohort?

THE CONSTRAINT SET this candidate has to satisfy. A mechanism that explains only the positives is not a
candidate. Everything below is an established result in this project, negatives included:

  POSITIVES
  P1  Burden stratifies 3-day death inside the guideline's highly-malignant tier, 29.5 % -> 73.1 %, +0.100 AUC
      over the category, calibrated (slope 0.980).
  P2  Replicates cross-system: I-CARE, +34.1 pp [+23.2, +44.2] among the already-suppressed.
  P3  Morphology adds +0.047 [+0.011, +0.083] over burden. Direction: bursts in early deaths are SHORT
      (1.84 s vs 2.87 s) and FAST (25.0 % vs 12.0 % of intra-burst power above 8 Hz).
  P4  Generalized slowing PRESENT marks survival, hugely: 74.9 % of >180-day survivors vs 29.7 % of <=3-day
      deaths. A larger contrast than burden's own.
  P5  Aetiology gap: suppression means more after anoxia than sepsis (log-odds +0.801 at the EEG).
  P6  Class A -- the excess is exhausted among 30-day survivors.

  NEGATIVES the candidate must ALSO survive
  N1  NOT a whole-body ischaemic dose marker (mediation 2.6 %; gradients steeper in sepsis than anoxia).
  N2  NOT depth, age, sex, coexisting findings, ceiling or scale artefact.
  N3  NOT label noise -- the gap reproduces under a blinded quantitative definition at every threshold.
  N4  NOT withdrawal as an explanation of the aetiology gap (halves both aetiologies; ratio 2.14 -> 2.17).
  N5  NOT drug-induced suppression (infusion commoner in anoxic; effect LARGER with drug present).
  N6  NOT "anoxic patients are simply sicker" (BS-negative mortality 32.8 % vs 32.7 %).
  N7  NOT a fixed quantity in the first 48 h after arrest -- I-CARE refuted that (ICC 0.584, agreement decays
      -0.370, trajectory coefficient +1.081 [+0.578, +1.614]).
  N8  Post-anoxic status epilepticus arises in SEVERELY injured brains, so "dead cortex cannot seize" is false
      here (PMID 36076090) -- any mechanism assuming silence-equals-severity is wrong.

THE CANDIDATE: THALAMOCORTICAL GENERATOR INTEGRITY.
Slow rhythms and long, organised bursts are produced by thalamocortical loops; fast fragmentary activity can be
generated by cortex alone. The proposal is that burden counts how much generator capacity is gone, while burst
MORPHOLOGY reports whether what remains is still thalamocortically organised.

  What it explains: P3 directly (long slow bursts = intact loop). P4 directly and better than burden does --
  slowing REQUIRES the loop, so its presence is a positive marker of function rather than absence of injury.
  P1 as the quantity-versus-quality pair. N1, because thalamus and cortex are what the measure is about.
  N8, because an injured-but-connected network can still seize; seizing is not evidence of health.
  What it STRUGGLES with: P5 and P6 -- it gives no account of why aetiology should change what suppression
  MEANS, beyond a hand-wave about selective vulnerability of thalamus and hippocampus to global ischaemia.
  And N7 sits awkwardly: if morphology reports a structural property it should be more stable over 48 h than
  burden is, which is a further test rather than a resolution.

  THE FALSIFIABLE PREDICTION TESTED HERE: in an independent post-arrest cohort, with OUR OWN detector, the
  SAME directions must hold -- survivors' bursts LONGER and with LESS high-frequency content -- and morphology
  must add discrimination over burden alone. If the directions invert or vanish, the candidate is dead.

WHY THIS ESCAPES THE TRAP THAT KILLED THE LAST MECHANISM TEST. The epileptogenicity test failed because its
outcome (GPD/LPD) overlapped the burst-suppression pattern itself, and the attempted fix conditioned on a
post-exposure collider. These features are measured WITHIN bursts, on the segments that are by definition not
suppressed, so no such overlap exists.
"""
import csv, io, os, re, sys
from concurrent.futures import ThreadPoolExecutor

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

AP = "arn:aws:s3:us-east-1:184438910517:accesspoint/bdsp-restricted-access-point"
ROOT = "ICARE_train/training/"
OUT = os.environ.get("ICARE_MORPH_OUT", "/tmp/eeg_probe/icare_morph.csv")
HOUR = float(os.environ.get("ICARE_HOUR", "24"))
THRESH = float(os.environ.get("ICARE_THRESH", "8.0"))
FRAME_S, MIN_RUN_S = 0.1, 0.5
PAIRS = [("FP1", "F3"), ("F3", "C3"), ("C3", "P3"), ("P3", "O1"),
         ("FP2", "F4"), ("F4", "C4"), ("C4", "P4"), ("P4", "O2")]


def s3c():
    import boto3
    from botocore.config import Config
    return boto3.Session(profile_name="physionet").client(
        "s3", region_name="us-east-1",
        config=Config(s3={"payload_signing_enabled": False}, max_pool_connections=32,
                      retries={"max_attempts": 3}))


_BP = {}


def bp(fs):
    from scipy.signal import butter
    if fs not in _BP:
        _BP[fs] = butter(4, [0.5 / (fs / 2), 40.0 / (fs / 2)], btype="band")
    return _BP[fs]


def parse_hea(txt):
    lines = [l for l in txt.splitlines() if l.strip()]
    first = lines[0].split()
    nsig = int(first[1]); fs = float(first[2])
    gains, bases, names = [], [], []
    for l in lines[1:1 + nsig]:
        p = l.split()
        m = re.match(r"([-\d.eE+]+)\(?(-?\d+)?\)?", p[2])
        g = float(m.group(1)); b = float(m.group(2) or 0)
        gains.append(g if g != 0 else 1.0); bases.append(b); names.append(p[-1])
    return fs, gains, bases, names


def morphology(x, fs):
    """Identical feature definitions to heedb_burst_morphology.py, so the cohorts are comparable."""
    fr = max(1, int(FRAME_S * fs))
    n = len(x) // fr
    if n < 50:
        return None
    seg = x[:n * fr].reshape(n, fr)
    ptp = seg.max(1) - seg.min(1)
    dead = ptp < 1e-9
    supp = (ptp < THRESH) & (~dead)
    need = max(1, int(MIN_RUN_S / FRAME_S))
    run = 0; sup = supp.copy()
    for i in range(n):
        if supp[i]:
            run += 1
        else:
            if run < need:
                sup[max(0, i - run):i] = False
            run = 0
    burden = float(sup.sum() / max(1, (~dead).sum()))

    # burst segments = maximal runs of non-suppressed frames
    segs, durs, amps = [], [], []
    i = 0
    while i < n:
        if not sup[i] and not dead[i]:
            j = i
            while j < n and not sup[j] and not dead[j]:
                j += 1
            if (j - i) * FRAME_S >= 0.5:
                segs.append(x[i * fr:j * fr])
                durs.append((j - i) * FRAME_S)
                amps.append(float(np.percentile(np.abs(x[i * fr:j * fr]), 95)))
            i = j
        else:
            i += 1
    if len(segs) < 4:
        return None

    ab = []
    for s in segs:
        if len(s) < int(0.5 * fs):
            continue
        f = np.fft.rfftfreq(len(s), 1.0 / fs)
        P = np.abs(np.fft.rfft(s * np.hanning(len(s)))) ** 2
        lo = (f >= 1) & (f <= 30); hi = (f >= 8) & (f <= 30)
        tot = P[lo].sum()
        if tot > 0:
            ab.append(float(P[hi].sum() / tot))
    return dict(n_bursts=len(segs), burst_dur=float(np.median(durs)),
                burst_amp=float(np.median(amps)),
                alpha_beta=(float(np.median(ab)) if ab else float("nan")),
                burst_rate=float(60.0 * len(segs) / max(len(x) / fs, 1e-9)),
                burden=burden)


def one_patient(pid, s3):
    import scipy.io as sio
    from scipy.signal import filtfilt
    try:
        r = s3.list_objects_v2(Bucket=AP, Prefix=f"{ROOT}{pid}/", MaxKeys=1000)
        eeg = [o["Key"] for o in r.get("Contents", []) if o["Key"].endswith("_EEG.mat")]
        if not eeg:
            return None

        def hr(k):
            m = re.match(r"^\d+_\d+_(\d+)_EEG\.mat$", k.split("/")[-1])
            return int(m.group(1)) if m else 10 ** 6
        eeg.sort(key=lambda k: abs(hr(k) - HOUR))
        key = eeg[0]; hour = hr(key)
        hea = s3.get_object(Bucket=AP, Key=key[:-4] + ".hea")["Body"].read().decode("utf-8", "replace")
        fs, gains, bases, names = parse_hea(hea)
        val = sio.loadmat(io.BytesIO(s3.get_object(Bucket=AP, Key=key)["Body"].read()))["val"]
        idx = {n.upper(): i for i, n in enumerate(names)}
        b, a = bp(fs)
        feats = []
        for u, v in PAIRS:
            if u in idx and v in idx:
                iu, iv = idx[u], idx[v]
                su = (val[iu].astype(np.float64) - bases[iu]) / gains[iu]
                sv = (val[iv].astype(np.float64) - bases[iv]) / gains[iv]
                d = su - sv
                if len(d) > 100:
                    try:
                        m = morphology(filtfilt(b, a, d), fs)
                        if m:
                            feats.append(m)
                    except Exception:
                        pass
        if not feats:
            return None
        # median across channels, as in the HEEDB extractor
        out = {k: float(np.median([f[k] for f in feats if f[k] == f[k]]))
               for k in ("n_bursts", "burst_dur", "burst_amp", "alpha_beta", "burst_rate", "burden")}
        out.update(pid=pid, hour=hour, fs=fs)
        return out
    except Exception:
        return None


def main():
    coh = [r["pid"] for r in csv.DictReader(open("/tmp/eeg_probe/icare_cohort.csv"))]
    done = set()
    if os.path.exists(OUT):
        done = {r["pid"] for r in csv.DictReader(open(OUT))}
    todo = [p for p in coh if p not in done]
    print(f"I-CARE burst morphology at ~hour {HOUR:.0f}: {len(todo)} to do ({len(done)} done)")
    newf = not os.path.exists(OUT)
    fh = open(OUT, "a", newline="")
    w = csv.writer(fh)
    cols = ["pid", "hour", "n_bursts", "burst_dur", "burst_amp", "alpha_beta", "burst_rate", "burden", "fs"]
    if newf:
        w.writerow(cols); fh.flush()
    s3 = s3c(); n = 0
    with ThreadPoolExecutor(max_workers=8) as ex:
        for res in ex.map(lambda p: one_patient(p, s3), todo):
            if res:
                w.writerow([res.get(c, "") for c in cols]); n += 1
            if n and n % 25 == 0:
                fh.flush(); print(f"  {n} written", flush=True)
    fh.close()
    print(f"DONE {n} -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
